package internal

import (
	_ "embed"
	"fmt"
	"strings"
	"text/template"
)

const (
	connectorOutputFile   = "connector.generated.go"
	schemaOutputJSONFile  = "schema.generated.json"
	schemaOutputGoFile    = "schema.generated.go"
	typeMethodsOutputFile = "types.generated.go"
)

//go:embed templates/connector/connector.go.tmpl
var connectorTemplateStr string
var connectorTemplate *template.Template

func init() {
	var err error
	connectorTemplate, err = template.New(connectorOutputFile).Parse(connectorTemplateStr)
	if err != nil {
		panic(fmt.Errorf("failed to parse connector template: %w", err))
	}
}

func writeFileHeader(builder *strings.Builder, packageName string) {
	_, _ = builder.WriteString(`// Code generated by github.com/hasura/ndc-sdk-go/cmd/hasura-ndc-go, DO NOT EDIT.
package `)
	_, _ = builder.WriteString(packageName)
	_, _ = builder.WriteRune('\n')
}

func writeIndent(builder *strings.Builder, num int) {
	for i := 0; i < num; i++ {
		_, _ = builder.WriteRune(' ')
	}
}

func writeErrorCheck(sb *strings.Builder, paramCount int, indent int) {
	sb.WriteRune('\n')
	writeIndent(sb, indent)
	sb.WriteString("if err != nil {\n")
	writeIndent(sb, indent)
	sb.WriteString("  return ")
	for i := 0; i < paramCount; i++ {
		if i == paramCount-1 {
			sb.WriteString("err")
		} else {
			sb.WriteString("nil, ")
		}
	}
	sb.WriteRune('\n')
	writeIndent(sb, indent)
	sb.WriteString("}\n")
}
