// Code generated by github.com/hasura/ndc-sdk-go/cmd/hasura-ndc-go, DO NOT EDIT.
package main

import (
	"github.com/hasura/ndc-sdk-go/schema"
	"github.com/hasura/ndc-sdk-go/utils"
)

// GetConnectorSchema gets the generated connector schema
func GetConnectorSchema() schema.SchemaResponse {
	return schema.SchemaResponse{
		Collections: []schema.CollectionInfo{},
		ObjectTypes: schema.SchemaResponseObjectTypes{
			"Author": schema.ObjectType{
				Fields: schema.ObjectTypeFields{
					"created_at": schema.ObjectField{
						Type: schema.NewNamedType("TimestampTZ").Encode(),
					},
					"tags": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNamedType("String")).Encode(),
					},
					"author": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Author")).Encode(),
					},
					"id": schema.ObjectField{
						Type: schema.NewNamedType("String").Encode(),
					},
				},
			},
			"CreateArticleArgumentsAuthor": schema.ObjectType{
				Fields: schema.ObjectTypeFields{
					"id": schema.ObjectField{
						Type: schema.NewNamedType("UUID").Encode(),
					},
					"created_at": schema.ObjectField{
						Type: schema.NewNamedType("TimestampTZ").Encode(),
					},
				},
			},
			"CreateArticleResult": schema.ObjectType{
				Fields: schema.ObjectTypeFields{
					"id": schema.ObjectField{
						Type: schema.NewNamedType("Int32").Encode(),
					},
					"authors": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNamedType("Author")).Encode(),
					},
				},
			},
			"CreateAuthorResult": schema.ObjectType{
				Fields: schema.ObjectTypeFields{
					"id": schema.ObjectField{
						Type: schema.NewNamedType("Int32").Encode(),
					},
					"name": schema.ObjectField{
						Type: schema.NewNamedType("String").Encode(),
					},
					"created_at": schema.ObjectField{
						Type: schema.NewNamedType("TimestampTZ").Encode(),
					},
				},
			},
			"GetArticlesResult": schema.ObjectType{
				Fields: schema.ObjectTypeFields{
					"id": schema.ObjectField{
						Type: schema.NewNamedType("String").Encode(),
					},
					"Name": schema.ObjectField{
						Type: schema.NewNamedType("String").Encode(),
					},
				},
			},
			"GetTypesArguments": schema.ObjectType{
				Fields: schema.ObjectTypeFields{
					"PtrArrayUint32Ptr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int32")))).Encode(),
					},
					"Object": schema.ObjectField{
						Type: schema.NewNamedType("GetTypesArgumentsObject").Encode(),
					},
					"NamedArrayPtr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("Author"))).Encode(),
					},
					"ArrayJSON": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNamedType("JSON")).Encode(),
					},
					"Uint16Ptr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int16")).Encode(),
					},
					"Uint32Ptr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int32")).Encode(),
					},
					"ArrayBigIntPtr": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("BigInt"))).Encode(),
					},
					"PtrArrayInt16": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("Int16"))).Encode(),
					},
					"PtrArrayUint": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("Int32"))).Encode(),
					},
					"PtrArrayInt8Ptr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int8")))).Encode(),
					},
					"PtrArrayUUIDPtr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("UUID")))).Encode(),
					},
					"Float32": schema.ObjectField{
						Type: schema.NewNamedType("Float32").Encode(),
					},
					"BytesPtr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Bytes")).Encode(),
					},
					"Int8Ptr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int8")).Encode(),
					},
					"ArrayIntPtr": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int32"))).Encode(),
					},
					"ArrayUUIDPtr": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("UUID"))).Encode(),
					},
					"PtrArrayInt": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("Int32"))).Encode(),
					},
					"PtrArrayInt32Ptr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int32")))).Encode(),
					},
					"PtrArrayRawJSONPtr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("RawJSON")))).Encode(),
					},
					"Int": schema.ObjectField{
						Type: schema.NewNamedType("Int32").Encode(),
					},
					"BoolPtr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"ArrayUint8": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNamedType("Int8")).Encode(),
					},
					"ObjectPtr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("GetTypesArgumentsObjectPtr")).Encode(),
					},
					"UUID": schema.ObjectField{
						Type: schema.NewNamedType("UUID").Encode(),
					},
					"ArrayBool": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNamedType("Boolean")).Encode(),
					},
					"ArrayFloat64Ptr": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Float64"))).Encode(),
					},
					"PtrArrayUint8": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("Int8"))).Encode(),
					},
					"PtrArrayUUID": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("UUID"))).Encode(),
					},
					"PtrArrayUintPtr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int32")))).Encode(),
					},
					"PtrArrayJSON": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("JSON"))).Encode(),
					},
					"Text": schema.ObjectField{
						Type: schema.NewNamedType("String").Encode(),
					},
					"NamedObjectPtr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Author")).Encode(),
					},
					"ArrayBoolPtr": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Boolean"))).Encode(),
					},
					"NamedArray": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNamedType("Author")).Encode(),
					},
					"DatePtr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Date")).Encode(),
					},
					"ArrayUintPtr": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int32"))).Encode(),
					},
					"ArrayRawJSONPtr": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("RawJSON"))).Encode(),
					},
					"Uint32": schema.ObjectField{
						Type: schema.NewNamedType("Int32").Encode(),
					},
					"ArrayBigInt": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNamedType("BigInt")).Encode(),
					},
					"PtrArrayBool": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("Boolean"))).Encode(),
					},
					"PtrArrayString": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("String"))).Encode(),
					},
					"MapPtr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
					"ArrayInt": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNamedType("Int32")).Encode(),
					},
					"PtrArrayRawJSON": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("RawJSON"))).Encode(),
					},
					"NamedObject": schema.ObjectField{
						Type: schema.NewNamedType("Author").Encode(),
					},
					"CustomScalar": schema.ObjectField{
						Type: schema.NewNamedType("CommentString").Encode(),
					},
					"ArrayInt32Ptr": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int32"))).Encode(),
					},
					"Uint": schema.ObjectField{
						Type: schema.NewNamedType("Int32").Encode(),
					},
					"PtrArrayInt64Ptr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int64")))).Encode(),
					},
					"ArrayUint8Ptr": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int8"))).Encode(),
					},
					"Int16Ptr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int16")).Encode(),
					},
					"ArrayUint32Ptr": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int32"))).Encode(),
					},
					"PtrArrayFloat64": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("Float64"))).Encode(),
					},
					"PtrArrayStringPtr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("String")))).Encode(),
					},
					"ArrayInt8Ptr": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int8"))).Encode(),
					},
					"UUIDPtr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("UUID")).Encode(),
					},
					"ArrayUUID": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNamedType("UUID")).Encode(),
					},
					"PtrArrayTime": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("TimestampTZ"))).Encode(),
					},
					"JSONPtr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
					"Float64": schema.ObjectField{
						Type: schema.NewNamedType("Float64").Encode(),
					},
					"Date": schema.ObjectField{
						Type: schema.NewNamedType("Date").Encode(),
					},
					"IntPtr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int32")).Encode(),
					},
					"Int32Ptr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int32")).Encode(),
					},
					"Int64Ptr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int64")).Encode(),
					},
					"ArrayObject": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNamedType("GetTypesArgumentsArrayObject")).Encode(),
					},
					"Bytes": schema.ObjectField{
						Type: schema.NewNamedType("Bytes").Encode(),
					},
					"Bool": schema.ObjectField{
						Type: schema.NewNamedType("Boolean").Encode(),
					},
					"PtrArrayUint16": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("Int16"))).Encode(),
					},
					"Time": schema.ObjectField{
						Type: schema.NewNamedType("TimestampTZ").Encode(),
					},
					"ArrayInt32": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNamedType("Int32")).Encode(),
					},
					"ArrayFloat32": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNamedType("Float32")).Encode(),
					},
					"ArrayTime": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNamedType("TimestampTZ")).Encode(),
					},
					"PtrArrayUint64": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("Int64"))).Encode(),
					},
					"PtrArrayUint8Ptr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int8")))).Encode(),
					},
					"PtrArrayFloat32Ptr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Float32")))).Encode(),
					},
					"JSON": schema.ObjectField{
						Type: schema.NewNamedType("JSON").Encode(),
					},
					"TextPtr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"Uint64": schema.ObjectField{
						Type: schema.NewNamedType("Int64").Encode(),
					},
					"Uint64Ptr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int64")).Encode(),
					},
					"Float64Ptr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Float64")).Encode(),
					},
					"BigIntPtr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("BigInt")).Encode(),
					},
					"PtrArrayInt32": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("Int32"))).Encode(),
					},
					"String": schema.ObjectField{
						Type: schema.NewNamedType("String").Encode(),
					},
					"StringPtr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"ArrayFloat32Ptr": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Float32"))).Encode(),
					},
					"ArrayTimePtr": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("TimestampTZ"))).Encode(),
					},
					"ArrayObjectPtr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("GetTypesArgumentsArrayObjectPtr"))).Encode(),
					},
					"BigInt": schema.ObjectField{
						Type: schema.NewNamedType("BigInt").Encode(),
					},
					"EnumPtr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("SomeEnum")).Encode(),
					},
					"PtrArrayInt16Ptr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int16")))).Encode(),
					},
					"PtrArrayUint16Ptr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int16")))).Encode(),
					},
					"RawJSONPtr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("RawJSON")).Encode(),
					},
					"Int32": schema.ObjectField{
						Type: schema.NewNamedType("Int32").Encode(),
					},
					"PtrArrayInt64": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("Int64"))).Encode(),
					},
					"PtrArrayBigInt": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("BigInt"))).Encode(),
					},
					"ArrayString": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNamedType("String")).Encode(),
					},
					"URL": schema.ObjectField{
						Type: schema.NewNamedType("URL").Encode(),
					},
					"ArrayUint16": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNamedType("Int16")).Encode(),
					},
					"PtrArrayJSONPtr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("JSON")))).Encode(),
					},
					"Enum": schema.ObjectField{
						Type: schema.NewNamedType("SomeEnum").Encode(),
					},
					"ArrayStringPtr": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("String"))).Encode(),
					},
					"PtrArrayBigIntPtr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("BigInt")))).Encode(),
					},
					"RawJSON": schema.ObjectField{
						Type: schema.NewNamedType("RawJSON").Encode(),
					},
					"Int64": schema.ObjectField{
						Type: schema.NewNamedType("Int64").Encode(),
					},
					"Uint8Ptr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int8")).Encode(),
					},
					"TimePtr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("TimestampTZ")).Encode(),
					},
					"ArrayInt16Ptr": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int16"))).Encode(),
					},
					"Uint16": schema.ObjectField{
						Type: schema.NewNamedType("Int16").Encode(),
					},
					"ArrayFloat64": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNamedType("Float64")).Encode(),
					},
					"PtrArrayFloat32": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("Float32"))).Encode(),
					},
					"PtrArrayTimePtr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("TimestampTZ")))).Encode(),
					},
					"Uint8": schema.ObjectField{
						Type: schema.NewNamedType("Int8").Encode(),
					},
					"ArrayInt64": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNamedType("Int64")).Encode(),
					},
					"ArrayUint64": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNamedType("Int64")).Encode(),
					},
					"ArrayInt64Ptr": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int64"))).Encode(),
					},
					"ArrayUint16Ptr": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int16"))).Encode(),
					},
					"ArrayUint64Ptr": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int64"))).Encode(),
					},
					"ArrayRawJSON": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNamedType("RawJSON")).Encode(),
					},
					"PtrArrayUint32": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("Int32"))).Encode(),
					},
					"UintPtr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Int32")).Encode(),
					},
					"PtrArrayFloat64Ptr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Float64")))).Encode(),
					},
					"ArrayUint": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNamedType("Int32")).Encode(),
					},
					"ArrayJSONPtr": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("JSON"))).Encode(),
					},
					"PtrArrayInt8": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("Int8"))).Encode(),
					},
					"Map": schema.ObjectField{
						Type: schema.NewNamedType("JSON").Encode(),
					},
					"Float32Ptr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("Float32")).Encode(),
					},
					"ArrayUint32": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNamedType("Int32")).Encode(),
					},
					"ArrayMapPtr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("JSON"))).Encode(),
					},
					"ArrayInt16": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNamedType("Int16")).Encode(),
					},
					"PtrArrayIntPtr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int32")))).Encode(),
					},
					"PtrArrayBoolPtr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Boolean")))).Encode(),
					},
					"Int16": schema.ObjectField{
						Type: schema.NewNamedType("Int16").Encode(),
					},
					"CustomScalarPtr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("CommentString")).Encode(),
					},
					"ArrayInt8": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNamedType("Int8")).Encode(),
					},
					"PtrArrayUint64Ptr": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int64")))).Encode(),
					},
					"ArrayMap": schema.ObjectField{
						Type: schema.NewArrayType(schema.NewNamedType("JSON")).Encode(),
					},
					"Int8": schema.ObjectField{
						Type: schema.NewNamedType("Int8").Encode(),
					},
				},
			},
			"GetTypesArgumentsArrayObject": schema.ObjectType{
				Fields: schema.ObjectTypeFields{
					"content": schema.ObjectField{
						Type: schema.NewNamedType("String").Encode(),
					},
				},
			},
			"GetTypesArgumentsArrayObjectPtr": schema.ObjectType{
				Fields: schema.ObjectTypeFields{
					"content": schema.ObjectField{
						Type: schema.NewNamedType("String").Encode(),
					},
				},
			},
			"GetTypesArgumentsObject": schema.ObjectType{
				Fields: schema.ObjectTypeFields{
					"id": schema.ObjectField{
						Type: schema.NewNamedType("UUID").Encode(),
					},
					"created_at": schema.ObjectField{
						Type: schema.NewNamedType("TimestampTZ").Encode(),
					},
				},
			},
			"GetTypesArgumentsObjectPtr": schema.ObjectType{
				Fields: schema.ObjectTypeFields{
					"Long": schema.ObjectField{
						Type: schema.NewNamedType("Int32").Encode(),
					},
					"Lat": schema.ObjectField{
						Type: schema.NewNamedType("Int32").Encode(),
					},
				},
			},
			"HelloResult": schema.ObjectType{
				Fields: schema.ObjectTypeFields{
					"foo": schema.ObjectField{
						Type: schema.NewNamedType("Foo").Encode(),
					},
					"error": schema.ObjectField{
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
					"id": schema.ObjectField{
						Type: schema.NewNamedType("UUID").Encode(),
					},
					"num": schema.ObjectField{
						Type: schema.NewNamedType("Int32").Encode(),
					},
					"text": schema.ObjectField{
						Type: schema.NewNamedType("String").Encode(),
					},
				},
			},
		},
		Functions: []schema.FunctionInfo{
			{
				Name:        "getBool",
				Description: utils.ToPtr("return an scalar boolean"),
				ResultType:  schema.NewNamedType("Boolean").Encode(),
				Arguments:   map[string]schema.ArgumentInfo{},
			},
			{
				Name:       "getTypes",
				ResultType: schema.NewNullableType(schema.NewNamedType("GetTypesArguments")).Encode(),
				Arguments: map[string]schema.ArgumentInfo{
					"BigIntPtr": {
						Type: schema.NewNullableType(schema.NewNamedType("BigInt")).Encode(),
					},
					"Uint16": {
						Type: schema.NewNamedType("Int16").Encode(),
					},
					"PtrArrayUint8Ptr": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int8")))).Encode(),
					},
					"PtrArrayBoolPtr": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Boolean")))).Encode(),
					},
					"PtrArrayInt16Ptr": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int16")))).Encode(),
					},
					"ArrayUint": {
						Type: schema.NewArrayType(schema.NewNamedType("Int32")).Encode(),
					},
					"PtrArrayJSONPtr": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("JSON")))).Encode(),
					},
					"ArrayFloat64Ptr": {
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Float64"))).Encode(),
					},
					"ArrayString": {
						Type: schema.NewArrayType(schema.NewNamedType("String")).Encode(),
					},
					"PtrArrayUUIDPtr": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("UUID")))).Encode(),
					},
					"PtrArrayFloat32": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("Float32"))).Encode(),
					},
					"Float32": {
						Type: schema.NewNamedType("Float32").Encode(),
					},
					"ArrayBool": {
						Type: schema.NewArrayType(schema.NewNamedType("Boolean")).Encode(),
					},
					"ArrayFloat32": {
						Type: schema.NewArrayType(schema.NewNamedType("Float32")).Encode(),
					},
					"PtrArrayFloat32Ptr": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Float32")))).Encode(),
					},
					"ArrayUint64Ptr": {
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int64"))).Encode(),
					},
					"PtrArrayFloat64Ptr": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Float64")))).Encode(),
					},
					"NamedObjectPtr": {
						Type: schema.NewNullableType(schema.NewNamedType("Author")).Encode(),
					},
					"ArrayInt32": {
						Type: schema.NewArrayType(schema.NewNamedType("Int32")).Encode(),
					},
					"EnumPtr": {
						Type: schema.NewNullableType(schema.NewNamedType("SomeEnum")).Encode(),
					},
					"Int64": {
						Type: schema.NewNamedType("Int64").Encode(),
					},
					"PtrArrayUint32": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("Int32"))).Encode(),
					},
					"PtrArrayStringPtr": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("String")))).Encode(),
					},
					"ArrayMapPtr": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("JSON"))).Encode(),
					},
					"PtrArrayUint16Ptr": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int16")))).Encode(),
					},
					"UUID": {
						Type: schema.NewNamedType("UUID").Encode(),
					},
					"String": {
						Type: schema.NewNamedType("String").Encode(),
					},
					"PtrArrayBigInt": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("BigInt"))).Encode(),
					},
					"PtrArrayBool": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("Boolean"))).Encode(),
					},
					"ArrayInt64": {
						Type: schema.NewArrayType(schema.NewNamedType("Int64")).Encode(),
					},
					"ArrayInt16Ptr": {
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int16"))).Encode(),
					},
					"PtrArrayUint64": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("Int64"))).Encode(),
					},
					"ArrayObjectPtr": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("GetTypesArgumentsArrayObjectPtr"))).Encode(),
					},
					"RawJSONPtr": {
						Type: schema.NewNullableType(schema.NewNamedType("RawJSON")).Encode(),
					},
					"ArrayBigInt": {
						Type: schema.NewArrayType(schema.NewNamedType("BigInt")).Encode(),
					},
					"UintPtr": {
						Type: schema.NewNullableType(schema.NewNamedType("Int32")).Encode(),
					},
					"JSON": {
						Type: schema.NewNamedType("JSON").Encode(),
					},
					"Float64Ptr": {
						Type: schema.NewNullableType(schema.NewNamedType("Float64")).Encode(),
					},
					"ArrayFloat64": {
						Type: schema.NewArrayType(schema.NewNamedType("Float64")).Encode(),
					},
					"ArrayUint8Ptr": {
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int8"))).Encode(),
					},
					"Float64": {
						Type: schema.NewNamedType("Float64").Encode(),
					},
					"UUIDPtr": {
						Type: schema.NewNullableType(schema.NewNamedType("UUID")).Encode(),
					},
					"Uint8Ptr": {
						Type: schema.NewNullableType(schema.NewNamedType("Int8")).Encode(),
					},
					"ArrayInt32Ptr": {
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int32"))).Encode(),
					},
					"PtrArrayString": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("String"))).Encode(),
					},
					"Time": {
						Type: schema.NewNamedType("TimestampTZ").Encode(),
					},
					"ArrayObject": {
						Type: schema.NewArrayType(schema.NewNamedType("GetTypesArgumentsArrayObject")).Encode(),
					},
					"ArrayInt8Ptr": {
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int8"))).Encode(),
					},
					"ArrayTimePtr": {
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("TimestampTZ"))).Encode(),
					},
					"PtrArrayInt8": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("Int8"))).Encode(),
					},
					"Uint8": {
						Type: schema.NewNamedType("Int8").Encode(),
					},
					"PtrArrayUintPtr": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int32")))).Encode(),
					},
					"ArrayFloat32Ptr": {
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Float32"))).Encode(),
					},
					"StringPtr": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"Uint64Ptr": {
						Type: schema.NewNullableType(schema.NewNamedType("Int64")).Encode(),
					},
					"Int8": {
						Type: schema.NewNamedType("Int8").Encode(),
					},
					"PtrArrayUUID": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("UUID"))).Encode(),
					},
					"PtrArrayInt32Ptr": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int32")))).Encode(),
					},
					"Enum": {
						Type: schema.NewNamedType("SomeEnum").Encode(),
					},
					"BytesPtr": {
						Type: schema.NewNullableType(schema.NewNamedType("Bytes")).Encode(),
					},
					"NamedArrayPtr": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("Author"))).Encode(),
					},
					"PtrArrayJSON": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("JSON"))).Encode(),
					},
					"NamedArray": {
						Type: schema.NewArrayType(schema.NewNamedType("Author")).Encode(),
					},
					"ArrayUint16": {
						Type: schema.NewArrayType(schema.NewNamedType("Int16")).Encode(),
					},
					"MapPtr": {
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
					"ArrayIntPtr": {
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int32"))).Encode(),
					},
					"ArrayBoolPtr": {
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Boolean"))).Encode(),
					},
					"Uint32": {
						Type: schema.NewNamedType("Int32").Encode(),
					},
					"IntPtr": {
						Type: schema.NewNullableType(schema.NewNamedType("Int32")).Encode(),
					},
					"ArrayTime": {
						Type: schema.NewArrayType(schema.NewNamedType("TimestampTZ")).Encode(),
					},
					"Int16": {
						Type: schema.NewNamedType("Int16").Encode(),
					},
					"PtrArrayBigIntPtr": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("BigInt")))).Encode(),
					},
					"PtrArrayTimePtr": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("TimestampTZ")))).Encode(),
					},
					"DatePtr": {
						Type: schema.NewNullableType(schema.NewNamedType("Date")).Encode(),
					},
					"ArrayUint32Ptr": {
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int32"))).Encode(),
					},
					"PtrArrayTime": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("TimestampTZ"))).Encode(),
					},
					"ArrayRawJSONPtr": {
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("RawJSON"))).Encode(),
					},
					"CustomScalarPtr": {
						Type: schema.NewNullableType(schema.NewNamedType("CommentString")).Encode(),
					},
					"Int64Ptr": {
						Type: schema.NewNullableType(schema.NewNamedType("Int64")).Encode(),
					},
					"Int8Ptr": {
						Type: schema.NewNullableType(schema.NewNamedType("Int8")).Encode(),
					},
					"ArrayInt8": {
						Type: schema.NewArrayType(schema.NewNamedType("Int8")).Encode(),
					},
					"CustomScalar": {
						Type: schema.NewNamedType("CommentString").Encode(),
					},
					"PtrArrayRawJSONPtr": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("RawJSON")))).Encode(),
					},
					"ObjectPtr": {
						Type: schema.NewNullableType(schema.NewNamedType("GetTypesArgumentsObjectPtr")).Encode(),
					},
					"Date": {
						Type: schema.NewNamedType("Date").Encode(),
					},
					"Bool": {
						Type: schema.NewNamedType("Boolean").Encode(),
					},
					"NamedObject": {
						Type: schema.NewNamedType("Author").Encode(),
					},
					"PtrArrayUint32Ptr": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int32")))).Encode(),
					},
					"ArrayUUIDPtr": {
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("UUID"))).Encode(),
					},
					"RawJSON": {
						Type: schema.NewNamedType("RawJSON").Encode(),
					},
					"PtrArrayUint64Ptr": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int64")))).Encode(),
					},
					"PtrArrayInt64": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("Int64"))).Encode(),
					},
					"Map": {
						Type: schema.NewNamedType("JSON").Encode(),
					},
					"ArrayInt": {
						Type: schema.NewArrayType(schema.NewNamedType("Int32")).Encode(),
					},
					"PtrArrayInt32": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("Int32"))).Encode(),
					},
					"Float32Ptr": {
						Type: schema.NewNullableType(schema.NewNamedType("Float32")).Encode(),
					},
					"Uint": {
						Type: schema.NewNamedType("Int32").Encode(),
					},
					"PtrArrayInt": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("Int32"))).Encode(),
					},
					"ArrayUint8": {
						Type: schema.NewArrayType(schema.NewNamedType("Int8")).Encode(),
					},
					"Int32Ptr": {
						Type: schema.NewNullableType(schema.NewNamedType("Int32")).Encode(),
					},
					"ArrayRawJSON": {
						Type: schema.NewArrayType(schema.NewNamedType("RawJSON")).Encode(),
					},
					"Int16Ptr": {
						Type: schema.NewNullableType(schema.NewNamedType("Int16")).Encode(),
					},
					"ArrayMap": {
						Type: schema.NewArrayType(schema.NewNamedType("JSON")).Encode(),
					},
					"Bytes": {
						Type: schema.NewNamedType("Bytes").Encode(),
					},
					"ArrayJSONPtr": {
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("JSON"))).Encode(),
					},
					"ArrayBigIntPtr": {
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("BigInt"))).Encode(),
					},
					"ArrayUint16Ptr": {
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int16"))).Encode(),
					},
					"PtrArrayUint16": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("Int16"))).Encode(),
					},
					"PtrArrayUint": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("Int32"))).Encode(),
					},
					"Int": {
						Type: schema.NewNamedType("Int32").Encode(),
					},
					"PtrArrayRawJSON": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("RawJSON"))).Encode(),
					},
					"Object": {
						Type: schema.NewNamedType("GetTypesArgumentsObject").Encode(),
					},
					"PtrArrayUint8": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("Int8"))).Encode(),
					},
					"BoolPtr": {
						Type: schema.NewNullableType(schema.NewNamedType("Boolean")).Encode(),
					},
					"ArrayJSON": {
						Type: schema.NewArrayType(schema.NewNamedType("JSON")).Encode(),
					},
					"Uint16Ptr": {
						Type: schema.NewNullableType(schema.NewNamedType("Int16")).Encode(),
					},
					"PtrArrayInt64Ptr": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int64")))).Encode(),
					},
					"TimePtr": {
						Type: schema.NewNullableType(schema.NewNamedType("TimestampTZ")).Encode(),
					},
					"Uint32Ptr": {
						Type: schema.NewNullableType(schema.NewNamedType("Int32")).Encode(),
					},
					"JSONPtr": {
						Type: schema.NewNullableType(schema.NewNamedType("JSON")).Encode(),
					},
					"PtrArrayFloat64": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("Float64"))).Encode(),
					},
					"ArrayInt16": {
						Type: schema.NewArrayType(schema.NewNamedType("Int16")).Encode(),
					},
					"PtrArrayInt16": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNamedType("Int16"))).Encode(),
					},
					"Uint64": {
						Type: schema.NewNamedType("Int64").Encode(),
					},
					"Text": {
						Type: schema.NewNamedType("String").Encode(),
					},
					"URL": {
						Type: schema.NewNamedType("URL").Encode(),
					},
					"TextPtr": {
						Type: schema.NewNullableType(schema.NewNamedType("String")).Encode(),
					},
					"ArrayUint32": {
						Type: schema.NewArrayType(schema.NewNamedType("Int32")).Encode(),
					},
					"PtrArrayInt8Ptr": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int8")))).Encode(),
					},
					"ArrayUUID": {
						Type: schema.NewArrayType(schema.NewNamedType("UUID")).Encode(),
					},
					"ArrayStringPtr": {
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("String"))).Encode(),
					},
					"ArrayUint64": {
						Type: schema.NewArrayType(schema.NewNamedType("Int64")).Encode(),
					},
					"Int32": {
						Type: schema.NewNamedType("Int32").Encode(),
					},
					"ArrayUintPtr": {
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int32"))).Encode(),
					},
					"PtrArrayIntPtr": {
						Type: schema.NewNullableType(schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int32")))).Encode(),
					},
					"ArrayInt64Ptr": {
						Type: schema.NewArrayType(schema.NewNullableType(schema.NewNamedType("Int64"))).Encode(),
					},
					"BigInt": {
						Type: schema.NewNamedType("BigInt").Encode(),
					},
				},
			},
			{
				Name:        "hello",
				Description: utils.ToPtr("sends a hello message"),
				ResultType:  schema.NewNullableType(schema.NewNamedType("HelloResult")).Encode(),
				Arguments:   map[string]schema.ArgumentInfo{},
			},
			{
				Name:        "getArticles",
				Description: utils.ToPtr("GetArticles"),
				ResultType:  schema.NewArrayType(schema.NewNamedType("GetArticlesResult")).Encode(),
				Arguments: map[string]schema.ArgumentInfo{
					"Limit": {
						Type: schema.NewNamedType("Float64").Encode(),
					},
				},
			},
		},
		Procedures: []schema.ProcedureInfo{
			{
				Name:        "create_article",
				Description: utils.ToPtr("CreateArticle"),
				ResultType:  schema.NewNullableType(schema.NewNamedType("CreateArticleResult")).Encode(),
				Arguments: map[string]schema.ArgumentInfo{
					"author": {
						Type: schema.NewNamedType("CreateArticleArgumentsAuthor").Encode(),
					},
				},
			},
			{
				Name:        "increase",
				Description: utils.ToPtr("Increase"),
				ResultType:  schema.NewNamedType("Int32").Encode(),
				Arguments:   map[string]schema.ArgumentInfo{},
			},
			{
				Name:        "createAuthor",
				Description: utils.ToPtr("creates an author"),
				ResultType:  schema.NewNullableType(schema.NewNamedType("CreateAuthorResult")).Encode(),
				Arguments: map[string]schema.ArgumentInfo{
					"name": {
						Type: schema.NewNamedType("String").Encode(),
					},
				},
			},
			{
				Name:        "createAuthors",
				Description: utils.ToPtr("creates a list of authors"),
				ResultType:  schema.NewArrayType(schema.NewNamedType("CreateAuthorResult")).Encode(),
				Arguments: map[string]schema.ArgumentInfo{
					"names": {
						Type: schema.NewArrayType(schema.NewNamedType("String")).Encode(),
					},
				},
			},
		},
		ScalarTypes: schema.SchemaResponseScalarTypes{
			"BigInt": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationBigInteger().Encode(),
			},
			"Boolean": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationBoolean().Encode(),
			},
			"Bytes": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationBytes().Encode(),
			},
			"CommentString": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationString().Encode(),
			},
			"Date": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationDate().Encode(),
			},
			"Float32": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationFloat32().Encode(),
			},
			"Float64": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationFloat64().Encode(),
			},
			"Foo": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationJSON().Encode(),
			},
			"Int16": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationInt16().Encode(),
			},
			"Int32": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationInt32().Encode(),
			},
			"Int64": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationInt64().Encode(),
			},
			"Int8": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationInt8().Encode(),
			},
			"JSON": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationJSON().Encode(),
			},
			"RawJSON": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationJSON().Encode(),
			},
			"SomeEnum": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationEnum([]string{"foo", "bar"}).Encode(),
			},
			"String": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationString().Encode(),
			},
			"TimestampTZ": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationTimestampTZ().Encode(),
			},
			"URL": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationString().Encode(),
			},
			"UUID": schema.ScalarType{
				AggregateFunctions:  schema.ScalarTypeAggregateFunctions{},
				ComparisonOperators: map[string]schema.ComparisonOperatorDefinition{},
				Representation:      schema.NewTypeRepresentationUUID().Encode(),
			},
		},
	}
}
