name: ndc-go
version: "${CLI_VERSION}"
shortDescription: "CLI plugin for Hasura ndc-go"
homepage: https://github.com/hasura/ndc-sdk-go
hidden: true
platforms:
  - selector: darwin-arm64
    uri: "https://github.com/hasura/ndc-sdk-go/releases/download/${CLI_VERSION}/hasura-ndc-go-darwin-arm64"
    sha256: "${MACOS_ARM64_SHA256}"
    bin: "hasura-ndc-go"
    files:
      - from: "./hasura-ndc-go-darwin-arm64"
        to: "hasura-ndc-go"
  - selector: linux-arm64
    uri: "https://github.com/hasura/ndc-sdk-go/releases/download/${CLI_VERSION}/hasura-ndc-go-linux-arm64"
    sha256: "${LINUX_ARM64_SHA256}"
    bin: "hasura-ndc-go"
    files:
      - from: "./hasura-ndc-go-linux-arm64"
        to: "hasura-ndc-go"
  - selector: darwin-amd64
    uri: "https://github.com/hasura/ndc-sdk-go/releases/download/${CLI_VERSION}/hasura-ndc-go-darwin-amd64"
    sha256: "${MACOS_AMD64_SHA256}"
    bin: "hasura-ndc-go"
    files:
      - from: "./hasura-ndc-go-darwin-amd64"
        to: "hasura-ndc-go"
  - selector: windows-amd64
    uri: "https://github.com/hasura/ndc-sdk-go/releases/download/${CLI_VERSION}/hasura-ndc-go-windows-amd64.exe"
    sha256: "${WINDOWS_AMD64_SHA256}"
    bin: "hasura-ndc-go.exe"
    files:
      - from: "./hasura-ndc-go-windows-amd64.exe"
        to: "hasura-ndc-go.exe"
  - selector: linux-amd64
    uri: "https://github.com/hasura/ndc-sdk-go/releases/download/${CLI_VERSION}/hasura-ndc-go-linux-amd64"
    sha256: "${LINUX_AMD64_SHA256}"
    bin: "hasura-ndc-go"
    files:
      - from: "./hasura-ndc-go-linux-amd64"
        to: "hasura-ndc-go"
