extensions:
  bearertokenauth:
    scheme: "Bearer"
    token: "randomtoken"

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
        auth:
          authenticator: bearertokenauth
      http:
        endpoint: "0.0.0.0:4318"
        auth:
          authenticator: bearertokenauth

exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:8889"

  debug:
    verbosity: detailed

processors:
  batch:
    send_batch_max_size: 100
    send_batch_size: 10
    timeout: 10s

  memory_limiter:
    check_interval: 1s
    limit_percentage: 65
    spike_limit_percentage: 20

service:
  extensions:
    - bearertokenauth
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/jaeger]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug]

    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheus]
